version: 2
updates:
  # Update Maven dependencies in pom.xml
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    target-branch: "dev"
    versioning-strategy: "increase" # Only bump to the next major version
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:51"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 10 # Maximum number of open PRs created by Dependabot
    reviewers:
      - "masum-wsd"
    assignees:
      - "masum-wsd" # your-github-username
  
  # Update GitHub Actions dependencies in workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "02:51"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 10
    reviewers:
      - "masum-wsd"
    assignees:
      - "masum-wsd" # your-github-username
    
