version: 2
updates:
  # Update Maven dependencies in pom.xml
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "sunday
      time: "09:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 8 # Maximum number of open PRs created by Dependabot
  
  # Update GitHub Actions dependencies in workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "sunday
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 8
    
