server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 200
#  servlet:
#    context-path: /masum 

# for swagger      
springdoc:
  swagger-ui:
    path: swagger-ui.html
    
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb+srv://masum-wsd:masum-wsd-db-password@mongo-cluster-of-masum.ba9aw.mongodb.net/
      database: journalDB
      auto-index-creation: true
  elasticsearch:
    cluster-nodes: http://localhost:9200
  main:
    allow-circular-references: true

# for actuator
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: edgardocs-wrapper
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus,env,metrics,beans,loggers,info 
# for object storage
minio:
  url: http://localhost:9000
  access:
    key: L0cB1po3VEvmSHIp5iym
  secret:
    key: O6Bqc8lGFZblVXq1XsRGRT4tPNuMRiDpriYCP6wC
  bucket:
    name: edgar-bucket
# for logging
logging:
  level:
    root: info
    console:
      level: info
