server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 200
#  servlet:
#    context-path: /masum 

# for swagger      
springdoc:
  swagger-ui:
    path: swagger-ui.html
    enabled: true
  show-actuator: true
spring:
  codec:
    max-in-memory-size: 100MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
    base-url: http://localhost:9411/
  elasticsearch:
    cluster-nodes: http://localhost:9200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/testrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# for actuator
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: docx_conversion_wrapper
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus,env,metrics,beans,loggers,info 
# for object storage
minio:
  url: http://localhost:7001
  access:
    key: wiROOy30mJA1MK2PqBZp
  secret:
    key: aRoWHcJS9OBc7xhqjMagFl7fMGZhZbCDmTW0pMNW
  bucket:
    name: edgar-bucket
# for logging
logging:
  level:
    root: warn
    console:
      level: warn
