server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 200
#  servlet:
#    context-path: /masum 

# for swagger      
springdoc:
  swagger-ui:
    path: swagger-ui.html
    
spring:
  codec:
    max-in-memory-size: 100MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb+srv://masum-wsd:masum-wsd-db-password@mongo-cluster-of-masum.ba9aw.mongodb.net/
      database: journalDB
      auto-index-creation: true
  elasticsearch:
    cluster-nodes: http://localhost:9200
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/testrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# for actuator
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: edgardocs-wrapper
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus,env,metrics,beans,loggers,info 
# for object storage
minio:
  url: http://localhost:9000
  access:
    key: y2OarhGk9Czxh0nc7vEh
  secret:
    key: wlXExtE3uX18jZHrzt5AIovkvVzsHdxe0N0XJbVf
  bucket:
    name: edgar-bucket
# for logging
logging:
  level:
    root: info
    console:
      level: info
      
sentry:
  dsn: https://7207c6cdf49550a43ffc89d4fcc5557c@o4508031348113408.ingest.us.sentry.io/4508031351717888
  send-default-pii: true
  max-request-body-size: medium
# Sentry Spring Boot integration allows more fine-grained SentryOptions configuration
  max-breadcrumbs: 150
# Logback integration configuration options
  logging.minimum-event-level: info
  logging.minimum-breadcrumb-level: debug
# Performance configuration
  traces-sample-rate: 1.0
  enable-tracing: true
  ignored-checkins: ignored_monitor_slug_1,ignored_monitor_slug_2
  debug: true
  enable-backpressure-handling: true
  enable-spotlight: true
  enable-metrics: true
