server:
  port: 7001
  tomcat:
    max-connections: 2000
    accept-count: 200
#  servlet:
#    context-path: /masum 

# for swagger      
springdoc:
  swagger-ui:
    path: swagger-ui.html
    
spring:
  data:
    mongodb:
      uri: mongodb+srv://masum-wsd:masum-wsd-db-password@mongo-cluster-of-masum.ba9aw.mongodb.net/
      database: journalDB
      auto-index-creation: true
  main:
    allow-circular-references: true
    
# for actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,env,metrics,beans,loggers,info

# for logging
logging:
  level:
    root: warn
    console:
      level: WARN
