services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk

#  fluentd:
#    image: fluent/fluentd:v1.17.1-debian-1.0
#    container_name: fluentd
#    environment:
#      - FLUENT_ELASTICSEARCH_HOST=elasticsearch
#      - FLUENT_ELASTICSEARCH_PORT=9200
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
#    volumes:
#      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
#      - fluentd_buffer:/fluentd/buffer
#    networks:
#      - efk
#    user: root
#    command: /bin/sh -c "gem install fluent-plugin-elasticsearch --no-document && chown -R fluent /fluentd && su fluent -c 'fluentd -c /fluentd/etc/fluent.conf'"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
networks:
  efk:
    driver: bridge

volumes:
  es_data:
    driver: local
  fluentd_buffer:
    driver: local
