name: CI/CD Pipeline with Dastardly (DAST Scan) and JUnit

on:
  push:
    branches: [ "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "dev" ]
  # schedule:
  #   - cron: '39 11 * * 0'
jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Run Dastardly to scan the local application
    - name: Run Dastardly Action Step
      continue-on-error: true
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'http://edgar.wsd.com/docxtohtml/'

    # Publish Test Report
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/dastardly-report.xml'
        require_tests: true
